version: "3"

services:
    api: 
      container_name: app_backend
      build: ./backend
      ports:
        - 3001:3001
      platform: linux/x86_64
      working_dir: /app/backend
      volumes: 
        - ./backend/src:/app-backend/src
      depends_on:
        - db
      environment:
        - MYSQL_HOST=db
      env_file:
        - ./backend/.env
      networks:
        - manager_products_net
    db:
      image: mysql:8.0.21
      container_name: app_db
      environment:
        MYSQL_ROOT_PASSWORD: password123
      ports:
        - 3306:3306
      networks:
        - manager_products_net 

networks: 
  manager_products_net:
    driver: bridge